## Merge game databases

### Steps
- pick a main dataset
- rename columns
- for each added dataset
    - rename columns
    - rename platforms
    - check column values for anomalies
    - merge dataset to main
    - join columns using priority functions

In [1]:
import pandas as pd
import numpy as np
import column_join as cj
# from resolvers import resolvers, pick_longer, pick_first, merge_genres

In [ ]:
# declare the constants
LAUNCHBOX_CSV = 'data/launchbox_games.csv'
GOG_CSV = 'data/gog_games.csv'


default_columns = [
'name',
'filename',
'summary',
'platform',
'release_date',
'release_year',
'genres',
'developer',
'publisher',
'players',
'cooperative',
'rating', # range 1-100
'user_rating' # range 1-10
]

### Launchbox
Lets choose the Launchbox dataset as our main to which we will merge other datasets

In [2]:
launchbox = pd.read_csv('csv/launchbox.csv')

/tmp/ipykernel_8530/1639964382.py:1: DtypeWarning: Columns (17,18,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  launchbox = pd.read_csv('csv/launchbox.csv')

In [4]:
# Display column names with index numbers
for idx, col in enumerate(launchbox.columns):
    print(f"{idx}: {col}")

0: N°
1: DatabaseID
2: Name
3: ReleaseYear
4: Overview
5: MaxPlayers
6: ReleaseType
7: Cooperative
8: VideoURL
9: CommunityRating
10: Platform
11: ESRB
12: CommunityRatingCount
13: Genres
14: Developer
15: Publisher
16: WikipediaURL
17: AlternateName_Australia
18: AlternateName_Brazil
19: AlternateName_China
20: AlternateName_Europe
21: AlternateName_France
22: AlternateName_Germany
23: AlternateName_Japan
24: AlternateName_Korea
25: AlternateName_NorthAmerica
26: AlternateName_Spain
27: AlternateName_UnitedStates
28: AlternateName_World

In [5]:
# keep these columns
launchbox = launchbox[['Name', 'ReleaseYear', 'Overview', 'MaxPlayers',
                      'Cooperative', 'Platform', 'CommunityRating', 
                      'Genres', 'Developer', 'Publisher']]

In [6]:
launchbox.rename(columns={'Name':'name',
                          'ReleaseYear' : 'release_year',
                          'Overview' : 'summary',
                          'MaxPlayers' : 'players',
                          'Cooperative' : 'cooperative',
                          'Platform' : 'platform',
                          'CommunityRating' : 'user_rating',
                          'Genres' : 'genres',
                          'Developer' : 'developer',
                          'Publisher' : 'publisher'}, inplace=True)

In [7]:
launchbox.head()

,name,release_year,summary,players,cooperative,platform,user_rating,genres,developer,publisher
0,20th Century Video Almanac,1993.0,"In The Best of Our Century, we've taken multim...",1.0,0,3DO Interactive Multiplayer,3.301418,Education,The Software Toolworks,The Software Toolworks
1,3D Atlas,1994.0,The World Isn't Flat. Why Should Your Atlas Be...,1.0,0,3DO Interactive Multiplayer,3.500000,Education,Electronic Arts,Electronic Arts
2,3DO Action Pak,1995.0,This is a four-game compilation pack that cont...,1.0,0,3DO Interactive Multiplayer,3.647436,Compilation,3DO,3DO
3,3DO de Shiru Miru Asobu Nakajima Miyuki,NaN,NaN,1.0,0,3DO Interactive Multiplayer,3.750000,NaN,NaN,Pony Canyon
4,3DO Demo Disc Program,NaN,A white binder with blue silk-screened art. Th...,NaN,0,3DO Interactive Multiplayer,3.330357,NaN,NaN,NaN

In [8]:
# double the user rating so it would be between 1-10
launchbox['user_rating'] = launchbox['user_rating'] * 2

### Merge with all_games

In [9]:
all_games = pd.read_csv('csv/all_games.csv')

In [10]:
all_games.head()

,name,platform,release_date,summary,meta_score,user_review
0,The Legend of Zelda: Ocarina of Time,Nintendo 64,"November 23, 1998","As a young boy, Link is tricked by Ganondorf, ...",99,9.1
1,Tony Hawk's Pro Skater 2,PlayStation,"September 20, 2000",As most major publishers' development efforts ...,98,7.4
2,Grand Theft Auto IV,PlayStation 3,"April 29, 2008",[Metacritic's 2008 PS3 Game of the Year; Also ...,98,7.7
3,SoulCalibur,Dreamcast,"September 8, 1999","This is a tale of souls and swords, transcendi...",98,8.4
4,Grand Theft Auto IV,Xbox 360,"April 29, 2008",[Metacritic's 2008 Xbox 360 Game of the Year; ...,98,7.9

In [11]:
# in user_review column, replace 'tbd' with None
all_games['user_review'] = all_games['user_review'].replace('tbd', np.nan)

In [12]:
# sort for duplicate removal such that non-empty user_review comes first
all_games = all_games.sort_values(['name', 'platform', 'user_review'])

# remove duplicates, keep first
print(len(all_games))
all_games = all_games.drop_duplicates(subset=['name', 'platform'], keep='first').sort_values(['name', 'platform'])
print(len(all_games))

18800
18690

In [13]:
all_games.columns

Index(['name', 'platform', 'release_date', 'summary', 'meta_score',
       'user_review'],
      dtype='object')

In [14]:
# meta_score and user_review columns need to be renamed
all_games.rename(columns={'meta_score':'rating', 'user_review' : 'user_rating'}, inplace=True)

In [15]:
# convert release date to timestamp
all_games['release_date'] = pd.to_datetime(all_games['release_date'])

In [16]:
# check distinct platform values on all_games
all_games['platform'].unique()

array([' Switch', ' Xbox One', ' Xbox', ' Xbox 360', ' PC',
       ' PlayStation 4', ' PlayStation 2', ' Wii', ' DS',
       ' PlayStation 3', ' Nintendo 64', ' PlayStation', ' PSP',
       ' GameCube', ' Dreamcast', ' Game Boy Advance', ' 3DS', ' Wii U',
       ' PlayStation 5', ' PlayStation Vita', ' Xbox Series X', ' Stadia'],
      dtype=object)

In [17]:
# remove leading space for all_games platform values
all_games['platform'] = all_games['platform'].apply(lambda x: x.strip())
all_games['platform'].unique()

array(['Switch', 'Xbox One', 'Xbox', 'Xbox 360', 'PC', 'PlayStation 4',
       'PlayStation 2', 'Wii', 'DS', 'PlayStation 3', 'Nintendo 64',
       'PlayStation', 'PSP', 'GameCube', 'Dreamcast', 'Game Boy Advance',
       '3DS', 'Wii U', 'PlayStation 5', 'PlayStation Vita',
       'Xbox Series X', 'Stadia'], dtype=object)

In [18]:
# distinct platform values on launchbox
launchbox['platform'].unique()

array(['3DO Interactive Multiplayer', 'Amstrad CPC', 'Android',
       'Aamber Pegasus', 'Acorn Archimedes', 'Acorn Atom',
       'Acorn Electron', 'Amstrad GX4000', 'Apple II', 'Arcade',
       'APF Imagination Machine', 'Apogee BK-01', 'Apple IIGS',
       'Apple iOS', 'Apple Mac OS', 'Atari 2600', 'Atari 5200',
       'Atari 800', 'Atari 7800', 'Atari Jaguar', 'Atari ST',
       'Atari Jaguar CD', 'Atari Lynx', 'BBC Microcomputer System',
       'ColecoVision', 'Commodore 128', 'Commodore 64', 'Atari XEGS',
       'Bally Astrocade', 'Bandai Super Vision 8000', 'Camputers Lynx',
       'Casio Loopy', 'Casio PV-1000', 'Coleco ADAM', 'Commodore Amiga',
       'Commodore Amiga CD32', 'Commodore CDTV', 'Commodore MAX Machine',
       'Commodore PET', 'Commodore VIC-20', 'Epoch Super Cassette Vision',
       'Exelvision EXL 100', 'Fujitsu FM Towns Marty', 'Microsoft MSX',
       'Commodore Plus 4', 'Dragon 32/64', 'EACA EG2000 Colour Genie',
       'Elektronika BK', 'Emerson Arcadia 2001', 'Enterprise',
       'Entex Adventure Vision', 'Epoch Game Pocket Computer',
       'Exidy Sorcerer', 'Fairchild Channel F', 'Fujitsu FM-7',
       'Funtech Super Acan', 'Game Wave Family Entertainment System',
       'GamePark GP32', 'GameWave', 'GCE Vectrex', 'Hartung Game Master',
       'Hector HRX', 'Interton VC 4000', 'Jupiter Ace', 'Linux',
       'Magnavox Odyssey', 'Magnavox Odyssey 2',
       'Matra and Hachette Alice', 'Mattel Aquarius', 'Mattel HyperScan',
       'Mattel Intellivision', 'Mega Duck', 'Memotech MTX512',
       'Microsoft Xbox', 'Microsoft Xbox 360', 'Microsoft MSX2',
       'Microsoft MSX2+', 'Microsoft Xbox One', 'MS-DOS',
       'Microsoft Xbox Series X/S', 'NEC PC-8801', 'NEC PC-9801', 'MUGEN',
       'Namco System 22', 'NEC PC-FX', 'NEC TurboGrafx-16',
       'NEC TurboGrafx-CD', 'Nintendo 3DS', 'Nintendo 64',
       'Nintendo 64DD', 'Nintendo DS', 'Nintendo Entertainment System',
       'Nintendo Famicom Disk System', 'Nintendo Game Boy',
       'Nintendo Game Boy Advance', 'Nintendo Game Boy Color',
       'Nintendo GameCube', 'Nintendo Game & Watch', 'Nintendo Switch',
       'Nintendo Pokemon Mini', 'Nintendo Satellaview', 'Nintendo Wii',
       'Nintendo Wii U', 'OpenBOR', 'Nintendo Virtual Boy',
       'Nokia N-Gage', 'Nuon', 'Oric Atmos', 'Othello Multivision',
       'Ouya', 'PC Engine SuperGrafx', 'Philips CD-i', 'Pinball',
       'ScummVM', 'Sega CD 32X', 'Sega Dreamcast', 'Sega Dreamcast VMU',
       'Sega Game Gear', 'Philips VG 5000', 'Philips Videopac+', 'PICO-8',
       'RCA Studio II', 'SAM Coupé', 'Sammy Atomiswave', 'Sega 32X',
       'Sega CD', 'Sega Genesis', 'Sega Master System', 'Sega Pico',
       'Sega Saturn', 'Sega Hikaru', 'Sega Model 1', 'Sega Model 2',
       'Sega Model 3', 'Sega Naomi', 'Sega Naomi 2', 'Sega SC-3000',
       'Sega SG-1000', 'Sharp X1', 'Sharp X68000', 'Sinclair ZX Spectrum',
       'Sega ST-V', 'Sega System 16', 'Sega System 32', 'Sega Triforce',
       'Sharp MZ-2500', 'SNK Neo Geo AES', 'Sony Playstation',
       'Sinclair ZX-81', 'SNK Neo Geo CD', 'SNK Neo Geo MVS',
       'SNK Neo Geo Pocket', 'SNK Neo Geo Pocket Color',
       'Sony Playstation 2', 'Sony Playstation 3', 'Sony Playstation 4',
       'Sony Playstation 5', 'Sony Playstation Vita', 'Sony PSP',
       'Sony PocketStation', 'Sony PSP Minis',
       'Super Nintendo Entertainment System', 'Windows', 'Sord M5',
       'Spectravideo', 'Taito Type X', 'Tandy TRS-80', 'Tapwave Zodiac',
       'Texas Instruments TI 99/4A', 'Tiger Game.com', 'Tomy Tutor',
       'TRS-80 Color Computer', 'Vector-06C', 'VTech CreatiVision',
       'VTech Socrates', 'VTech V.Smile', 'Watara Supervision',
       'Web Browser', 'Windows 3.X', 'WonderSwan', 'WonderSwan Color',
       'WoW Action Max', 'XaviXPORT', 'ZiNc'], dtype=object)

In [19]:
# platform rename map for all_games to match launchbox platform names
platform_rename_map = {
    'PlayStation': 'Sony Playstation',
    'PlayStation 2': 'Sony Playstation 2',
    'PlayStation 3': 'Sony Playstation 3',
    'PlayStation 4': 'Sony Playstation 4',
    'PlayStation 5': 'Sony Playstation 5',
    'PlayStation Vita': 'Sony Playstation Vita',
    'PSP': 'Sony PSP',
    'Dreamcast' : 'Sega Dreamcast VMU',
    'Xbox 360' : 'Microsoft Xbox 360',
    'Xbox' : 'Microsoft Xbox',
    'Xbox One' : 'Microsoft Xbox One',
    'Xbox Series X' : 'Microsoft Xbox Series X',
    'Wii' : 'Nintendo Wii',
    'Wii U' : 'Nintendo Wii U',
    'Switch' : 'Nintendo Switch',
    'GameCube' : 'Nintendo GameCube',
    'Game Boy Advance' : 'Nintendo Game Boy Advance',
    '3DS' : 'Nintendo 3DS',
    'DS' : 'Nintendo DS',
    'Stadia' : 'Google Stadia',
    'PC' : 'Windows'
}

In [20]:
all_games['platform'] = all_games['platform'].replace(platform_rename_map)

In [21]:
stacked_df = pd.concat([all_games, launchbox], ignore_index=True)

In [28]:
# --- Resolver Functions ---
def pick_first(series):
    return series.dropna().iloc[0] if series.notna().any() else np.nan

# pick the longest. used for description fields
def pick_longer(series):
    if series.notna().any():
        return max(series.dropna(), key=len)
    return np.nan

def merge_genres(series):
    return ", ".join(sorted(set(series.dropna()))) if series.notna().any() else np.nan

# --- Resolver Dictionary ---
resolvers = {
    "rating": pick_first,
    "user_rating": pick_first,
    "developer": pick_first,
    "publisher": pick_first,
    "release_year": "max",          
    "genres": merge_genres,
    "players": "any",
    "cooperative": "any",
    "summary": pick_longer
}

In [25]:
stacked_df.columns

Index(['name', 'platform', 'release_date', 'summary', 'rating', 'user_rating',
       'release_year', 'players', 'cooperative', 'genres', 'developer',
       'publisher'],
      dtype='object')

In [29]:
merged_df = stacked_df.groupby(['name', 'platform'], as_index=False).agg(resolvers)

In [30]:
merged_df.head()

,name,platform,rating,user_rating,developer,publisher,release_year,genres,players,cooperative,summary
0,! That Bastard Is Trying To Steal Our Gold !,Windows,NaN,8.0,WTFOMGames,WTFOMGames,NaN,Platform; Puzzle,False,False,Steal gold from the Lerpikon's dungeons! Get r...
1,!!!Ants!!!,Tandy TRS-80,NaN,5.0,Brian Rotolante,Synergistic Solar Inc.,1979.0,NaN,True,False,In Ants you can become an ant and join the ran...
2,"""300""",Pinball,NaN,6.944444,Gottlieb,Gottlieb,1975.0,Pinball,True,False,"""300"" (the exact machine name includes the quo..."
3,"""8 Ball""",Pinball,NaN,7.25,Williams Electronic Games,Williams Electronic Games,1952.0,Pinball,True,False,A pool table themed pinball game from Williams...
4,"""History in the Making"": The First Three Years",Amstrad CPC,NaN,6.972222,NaN,U.S. Gold,1988.0,Compilation,True,False,A celebration of U.S. Gold's first three years...

In [22]:
# lets try merging
merged_df = pd.merge(launchbox, all_games, on=['name', 'platform'], how='outer', validate="many_to_many")

In [23]:
merged_df.head()

,name,release_year,summary_x,players,cooperative,platform,user_rating_x,genres,developer,publisher,release_date,summary_y,rating,user_rating_y
0,! That Bastard Is Trying To Steal Our Gold !,NaN,Steal gold from the Lerpikon's dungeons! Get r...,NaN,0.0,Windows,8.000000,Platform; Puzzle,WTFOMGames,WTFOMGames,NaT,NaN,NaN,NaN
1,!!!Ants!!!,1979.0,In Ants you can become an ant and join the ran...,1.0,0.0,Tandy TRS-80,5.000000,NaN,Brian Rotolante,Synergistic Solar Inc.,NaT,NaN,NaN,NaN
2,"""300""",1975.0,"""300"" (the exact machine name includes the quo...",4.0,0.0,Pinball,6.944444,Pinball,Gottlieb,Gottlieb,NaT,NaN,NaN,NaN
3,"""8 Ball""",1952.0,A pool table themed pinball game from Williams...,2.0,0.0,Pinball,7.250000,Pinball,Williams Electronic Games,Williams Electronic Games,NaT,NaN,NaN,NaN
4,"""History in the Making"": The First Three Years",1988.0,A celebration of U.S. Gold's first three years...,4.0,0.0,Amstrad CPC,6.972222,Compilation,NaN,U.S. Gold,NaT,NaN,NaN,NaN

In [24]:
# create user_rating column from user_rating_x and user_rating_y with a preference for user_rating_y if it exists
merged_df['user_rating'] = merged_df['user_rating_y'].fillna(merged_df['user_rating_x'])

In [25]:
merged_df['summary'] = merged_df.apply(cj.prioritize_summary, args=['summary_x', 'summary_y'], axis=1)

In [26]:
# drop user_rating_x, user_rating_y, summary_x, summary_y
merged_df = merged_df.drop(['user_rating_x', 'user_rating_y','summary_x','summary_y'], axis=1)

In [27]:
merged_df.head()

,name,release_year,players,cooperative,platform,genres,developer,publisher,release_date,rating,user_rating,summary
0,! That Bastard Is Trying To Steal Our Gold !,NaN,NaN,0.0,Windows,Platform; Puzzle,WTFOMGames,WTFOMGames,NaT,NaN,8.0,Steal gold from the Lerpikon's dungeons! Get r...
1,!!!Ants!!!,1979.0,1.0,0.0,Tandy TRS-80,NaN,Brian Rotolante,Synergistic Solar Inc.,NaT,NaN,5.0,In Ants you can become an ant and join the ran...
2,"""300""",1975.0,4.0,0.0,Pinball,Pinball,Gottlieb,Gottlieb,NaT,NaN,6.944444,"""300"" (the exact machine name includes the quo..."
3,"""8 Ball""",1952.0,2.0,0.0,Pinball,Pinball,Williams Electronic Games,Williams Electronic Games,NaT,NaN,7.25,A pool table themed pinball game from Williams...
4,"""History in the Making"": The First Three Years",1988.0,4.0,0.0,Amstrad CPC,Compilation,NaN,U.S. Gold,NaT,NaN,6.972222,A celebration of U.S. Gold's first three years...

### GameTDB

In [28]:
gametdb = pd.read_csv('csv/games_on_gametdb.csv')

In [29]:
gametdb.head()

,N°,gametdb_id,gametdb_type,gametdb_region,gametdb_languages,gametdb_title_de,gametdb_title_en,gametdb_title_es,gametdb_title_fr,gametdb_title_it,...,gametdb_players,gametdb_genre,gametdb_rom,gametdb_rom_sans_ext,gametdb_platform,gametdb_title_cn,gametdb_title_tw,gametdb_synopsis_cn,gametdb_synopsis_tw,gametdb_rom_cleaned
0,1108862,A22J,3DS,NTSC-J,JP,Bokujou Monogatari Futago no Mura+,Bokujou Monogatari Futago no Mura+,NaN,Bokujou Monogatari Futago no Mura+,Bokujou Monogatari Futago no Mura+,...,1.0,NaN,Bokujou Monogatari Futago no Mura+ (Japan) (JA...,Bokujou Monogatari Futago no Mura+ (Japan) (JA),3DS,Bokujou Monogatari Futago no Mura+,Bokujou Monogatari Futago no Mura+,NaN,NaN,Bokujou Monogatari Futago no Mura+
1,1108863,A2AA,3DS,NaN,"EN,FR,DE,ES,IT,JP,KR,TW",Pokémon Ultrasonne: Update,Pokémon Ultra Sun,Pokémon Ultra Sun Actualización Ver. 1.2,Pokémon Ultra-Soleil: Mise à jour,Pokémon Ultrasole: Aggiornamenti,...,1.0,"role-playing,action rpg","Pokémon Ultra Sun (EN,FR,DE,ES,IT,JA,KO,ZHTW).3ds","Pokémon Ultra Sun (EN,FR,DE,ES,IT,JA,KO,ZHTW)",3DS,Pokémon Ultra Sun,更新資料 Ver. 1.2 精靈寶可夢 究極之日,An update for Pokémon™ Ultra Sun is now availa...,Nintendo 3DS遊戲軟體『精靈寶可夢 究極之日』的更新資料。\n持有『精靈寶可夢 究...,Pokémon Ultra Sun
2,1108864,A2AE,3DS,NTSC-U,EN,Pokémon Ultra Sun,Pokémon Ultra Sun,NaN,Pokémon Ultra Sun,Pokémon Ultra Sun,...,1.0,"adventure,role-playing,action rpg",Pokémon Ultra Sun (USA) (EN).3ds,Pokémon Ultra Sun (USA) (EN),3DS,Pokémon Ultra Sun,Pokémon Ultra Sun,NaN,NaN,Pokémon Ultra Sun
3,1108865,A2AJ,3DS,NTSC-J,JP,Pokémon Ultra Sun,Pokémon Ultra Sun,NaN,Pokémon Ultra Sun,Pokémon Ultra Sun,...,1.0,"adventure,role-playing,action rpg",Pokémon Ultra Sun (Japan) (JA).3ds,Pokémon Ultra Sun (Japan) (JA),3DS,Pokémon Ultra Sun,Pokémon Ultra Sun,NaN,NaN,Pokémon Ultra Sun
4,1108866,A2AK,3DS,NTSC-K,KR,Pokémon Ultra Sun,Pokémon Ultra Sun,NaN,Pokémon Ultra Sun,Pokémon Ultra Sun,...,1.0,"role-playing,action rpg",Pokémon Ultra Sun (Korea) (KO).3ds,Pokémon Ultra Sun (Korea) (KO),3DS,Pokémon Ultra Sun,Pokémon Ultra Sun,NaN,NaN,Pokémon Ultra Sun

In [30]:
gametdb.columns

Index(['N°', 'gametdb_id', 'gametdb_type', 'gametdb_region',
       'gametdb_languages', 'gametdb_title_de', 'gametdb_title_en',
       'gametdb_title_es', 'gametdb_title_fr', 'gametdb_title_it',
       'gametdb_title_ja', 'gametdb_title_ko', 'gametdb_title_nl',
       'gametdb_title_pt', 'gametdb_title_ru', 'gametdb_synopsis_de',
       'gametdb_synopsis_en', 'gametdb_synopsis_es', 'gametdb_synopsis_fr',
       'gametdb_synopsis_it', 'gametdb_synopsis_ja', 'gametdb_synopsis_ko',
       'gametdb_synopsis_nl', 'gametdb_synopsis_pt', 'gametdb_synopsis_ru',
       'gametdb_developer', 'gametdb_publisher', 'gametdb_date',
       'gametdb_players', 'gametdb_genre', 'gametdb_rom',
       'gametdb_rom_sans_ext', 'gametdb_platform', 'gametdb_title_cn',
       'gametdb_title_tw', 'gametdb_synopsis_cn', 'gametdb_synopsis_tw',
       'gametdb_rom_cleaned'],
      dtype='object')

In [31]:
gametdb.rename(columns={'gametdb_platform' : 'platform', 
                        'gametdb_title_en' : 'name',
                        'gametdb_synopsis_en' : 'summary', 
                        'gametdb_developer' : 'developer',
                        'gametdb_publisher' : 'publisher', 
                        'gametdb_date' : 'release_date', 
                        'gametdb_players' : 'players',
                        'gametdb_genre' : 'genres'
                        }, inplace=True)

In [32]:
gametdb = gametdb[['platform', 'name', 'summary', 
                   'developer', 'publisher', 'release_date', 
                   'players', 'genres']]

In [33]:
# convert release_date to timestamp
gametdb['release_date'] = pd.to_datetime(gametdb['release_date'])

In [34]:
# drop where 'name' is missing
gametdb = gametdb.dropna(subset=['name'])

In [35]:
# check name platform duplicates
duplicates = gametdb[gametdb.duplicated(subset=['name', 'platform'], keep=False)].sort_values(['name', 'platform', 'summary', 'developer', 'publisher'])
duplicates.head()

,platform,name,summary,developer,publisher,release_date,players,genres
34712,Switch,#Funtime,NaN,One Guy Games,The Quantum Astrophysicists Guild,1980-01-01,1.0,"music,action,arcade"
34713,Switch,#Funtime,NaN,One Guy Games,The Quantum Astrophysicists Guild,1980-01-01,1.0,"action,music,arcade,shooter"
16816,PS3,&: Sora no Mukou de Saki Masuyou ni,NaN,NaN,NaN,2014-01-01,1.0,NaN
21385,PS3,&: Sora no Mukou de Saki Masuyou ni,NaN,NaN,NaN,2014-01-01,1.0,NaN
52281,WiiU,(Event Preview) Extreme Exorcism,NaN,Golden Ruby Games,Ripstone,2018-01-01,1.0,"action,platformer,arcade"

In [36]:
# sort for duplicate removal such that the non-empty value for each column comes first
gametdb = gametdb.sort_values(['name', 'platform', 'summary', 'developer', 'publisher'])

# remove duplicates, keep first
print(len(gametdb))
gametdb = gametdb.drop_duplicates(subset=['name', 'platform'], keep='first').sort_values(['name', 'platform'])
print(len(gametdb))

52940
38272

In [37]:
merged_df['platform'].unique()

array(['Windows', 'Tandy TRS-80', 'Pinball', 'Amstrad CPC',
       'Sinclair ZX Spectrum', 'Atari 800', 'Atari ST', 'Commodore 64',
       'Commodore Amiga', 'Apple II', 'Nintendo Switch', 'Android',
       'Microsoft Xbox One', 'Microsoft Xbox', 'Sony Playstation 3',
       'Sony Playstation 4', 'Sony Playstation Vita', 'Acorn Electron',
       'BBC Microcomputer System', 'Arcade',
       'Nintendo Entertainment System',
       'Super Nintendo Entertainment System', 'Sony Playstation',
       'Commodore PET', 'MS-DOS', 'Microsoft Xbox 360', 'Microsoft MSX',
       'Commodore Plus 4', 'Sony PSP', 'WoW Action Max',
       'Sony Playstation 2', 'Sega SC-3000', 'Sega SG-1000', 'ScummVM',
       'Nintendo Wii', 'Nintendo Wii U', 'Nintendo GameCube',
       'Texas Instruments TI 99/4A', 'Nintendo DS',
       'Nintendo Game Boy Advance', 'Nintendo 64',
       'Nintendo Game Boy Color', 'Sinclair ZX-81', 'Nintendo 3DS',
       'Sega Genesis', 'Nintendo Game Boy', 'Exelvision EXL 100',
       'Apple iOS', 'Ouya', 'Commodore 128', 'Sony PSP Minis',
       'Apple Mac OS', 'NEC PC-8801', 'Windows 3.X', 'NEC PC-9801',
       'Sega Pico', 'Web Browser', 'Epoch Game Pocket Computer',
       'Microsoft MSX2', 'Sharp X68000', 'Sharp X1', 'NEC TurboGrafx-16',
       'NEC TurboGrafx-CD', 'Commodore CDTV', 'Atari 2600',
       'Sega Dreamcast', 'Sega Dreamcast VMU', 'Sega Naomi', 'PICO-8',
       'PC Engine SuperGrafx', 'Fujitsu FM-7', 'Linux', 'Philips CD-i',
       'Nintendo Famicom Disk System', 'Watara Supervision',
       'Sega Master System', 'Commodore Amiga CD32', 'ColecoVision',
       'Coleco ADAM', 'VTech CreatiVision', 'Microsoft MSX2+',
       'Fairchild Channel F', 'Jupiter Ace', 'TRS-80 Color Computer',
       'Acorn Archimedes', 'Fujitsu FM Towns Marty', 'Apple IIGS',
       '3DO Interactive Multiplayer', 'Bally Astrocade', 'Acorn Atom',
       'Sega Saturn', 'Commodore VIC-20', 'Mega Duck', 'OpenBOR',
       'SNK Neo Geo AES', 'SNK Neo Geo CD', 'Sega CD',
       'Nintendo Game & Watch', 'Nintendo Virtual Boy', 'Atari 7800',
       'Emerson Arcadia 2001', 'Mattel Aquarius', 'Oric Atmos',
       'Sony Playstation 5', 'Taito Type X', 'GCE Vectrex',
       'Dragon 32/64', 'EACA EG2000 Colour Genie', 'Camputers Lynx',
       'Memotech MTX512', 'Game Wave Family Entertainment System',
       'GameWave', 'Magnavox Odyssey 2', 'Philips Videopac+',
       'Mattel Intellivision', 'Sega Game Gear', 'ZiNc', 'Atari Lynx',
       'Microsoft Xbox Series X/S', 'Sharp MZ-2500', 'Atari 5200',
       'Vector-06C', 'Atari Jaguar CD', 'NEC PC-FX', 'Sega System 16',
       'Atari XEGS', 'VTech V.Smile', 'Nintendo Satellaview',
       'Hector HRX', 'Sord M5', 'Enterprise', 'Exidy Sorcerer',
       'Sega 32X', 'Namco System 22', 'Sega System 32', 'Sega Hikaru',
       'Interton VC 4000', 'Atari Jaguar', 'Matra and Hachette Alice',
       'Microsoft Xbox Series X', 'WonderSwan Color', 'Nokia N-Gage',
       'MUGEN', 'VTech Socrates', 'Casio PV-1000', 'Magnavox Odyssey',
       'WonderSwan', 'Sammy Atomiswave', 'Tapwave Zodiac', 'Casio Loopy',
       'Elektronika BK', 'Spectravideo', 'RCA Studio II', 'GamePark GP32',
       'Sega ST-V', 'Epoch Super Cassette Vision', 'SAM Coupé',
       'Commodore MAX Machine', 'Amstrad GX4000',
       'APF Imagination Machine', 'Philips VG 5000', 'Apogee BK-01',
       'Nuon', 'SNK Neo Geo MVS', 'Tomy Tutor', 'XaviXPORT',
       'SNK Neo Geo Pocket', 'SNK Neo Geo Pocket Color',
       'Nintendo Pokemon Mini', 'Tiger Game.com', 'Sega Naomi 2',
       'Bandai Super Vision 8000', 'Sega Model 2', 'Mattel HyperScan',
       'Sony PocketStation', 'Hartung Game Master', 'Funtech Super Acan',
       'Othello Multivision', 'Sega CD 32X', 'Sega Model 3',
       'Entex Adventure Vision', 'Nintendo 64DD', 'Sega Triforce',
       'Aamber Pegasus', 'Google Stadia', 'Sega Model 1'], dtype=object)

In [38]:
# check platform unique values
gametdb['platform'].unique()

array(['Switch', 'PS3', 'Wii', 'DS', 'WiiU', '3DS'], dtype=object)

In [39]:
platform_rename_map = {
    '3DS' : 'Nintendo 3DS',
    'DS' : 'Nintendo DS',
    'PS3' : 'Sony Playstation 3',
    'Switch' : 'Nintendo Switch',
    'Wii' : 'Nintendo Wii', 
    'WiiU' : 'Nintendo Wii U'
}

In [40]:
gametdb['platform'] = gametdb['platform'].replace(platform_rename_map)

In [41]:
gametdb.head()

,platform,name,summary,developer,publisher,release_date,players,genres
29454,Nintendo Switch,#1 Anagrams,NaN,NaN,Eclipse Games,2021-05-14,1.0,"board game,puzzle"
30900,Nintendo Switch,#1 Anagrams Sudokus Bundle,NaN,NaN,Eclipse Games,2022-02-25,1.0,"puzzle,board game"
28957,Nintendo Switch,#1 Crosswords,NaN,NaN,Eclipse Games,2021-02-19,1.0,puzzle
29271,Nintendo Switch,#1 Crosswords Bundle,NaN,NaN,Eclipse Games,2021-06-25,1.0,"board game,puzzle"
29272,Nintendo Switch,#1 Crosswords Sudokus Bundle,NaN,NaN,Eclipse Games,1980-01-01,1.0,"puzzle,board game"

#### Merging gametdb with main

In [42]:
# lets try merging
merged_df = pd.merge(merged_df, gametdb, on=['name', 'platform'], how='outer', validate="many_to_many")

In [43]:
merged_df = merged_df.replace({np.nan : None})

In [44]:
merged_df.columns

Index(['name', 'release_year', 'players_x', 'cooperative', 'platform',
       'genres_x', 'developer_x', 'publisher_x', 'release_date_x', 'rating',
       'user_rating', 'summary_x', 'summary_y', 'developer_y', 'publisher_y',
       'release_date_y', 'players_y', 'genres_y'],
      dtype='object')

In [45]:
merged_df['release_date'] = merged_df.apply(cj.prioritize_value, args=['release_date_x', 'release_date_y'], axis=1)
merged_df['players'] = merged_df.apply(cj.prioritize_value, args=['players_x', 'players_y'], axis=1)
merged_df['genres'] = merged_df.apply(cj.join_genres, args=['genres_x', 'genres_y'], axis=1)
merged_df['developer'] = merged_df.apply(cj.prioritize_columns, args=['developer_x', 'developer_y'], axis=1)
merged_df['publisher'] = merged_df.apply(cj.prioritize_columns, args=['publisher_x', 'publisher_y'], axis=1)
merged_df['summary'] = merged_df.apply(cj.prioritize_summary, args=['summary_x', 'summary_y'], axis=1)

In [46]:
# drop user_rating_x, user_rating_y, summary_x, summary_y
merged_df = merged_df.drop(['players_x', 'players_y',
                            'summary_x','summary_y',
                            'developer_x', 'developer_y',
                            'publisher_x', 'publisher_y',
                            'release_date_x', 'release_date_y',
                            'genres_x', 'genres_y'], axis=1)

### DAT DOS dataset

In [55]:
dat_dos = pd.read_csv('csv/dat_database_dos.csv')

In [56]:
dat_dos.head()

,ID,gametitle_mame,developer_mame,year_mame,genre_mame,description_mame,publisher_mame
0,61191,Stunt Island,The Assembly Line,19920101T000000,"Flight Simulator,Vehicle Simulation",Stunt Island was marketed as The Stunt Flying ...,"Walt Disney Computer Software, Inc."
1,61192,Tommy's Yahtzee,Tommy's Toys,19860101T000000,Board / Party Game,Tommy's Yahtzee is a shareware implementation ...,Freeware
2,61193,Fantasy Empires,Silicon Knights,19931001T000000,Strategy,Build and control an Empire! In Fantasy Empire...,"Strategic Simulations, Inc."
3,61194,Pune,Hardware Not Included,19950101T000000,Action,Pune is a light cycle/snake-type game for mult...,Hardware Not Included
4,61195,Mortal Kombat,Probe Software Ltd.,19940525T000000,"Action,Fighting","Five Hundred years ago, an ancient and well re...","Acclaim Entertainment, Inc."

In [57]:
dat_dos.isnull().sum()

ID                   0
gametitle_mame       0
developer_mame       3
year_mame            0
genre_mame           1
description_mame    12
publisher_mame      31
dtype: int64

In [58]:
dat_dos['platform'] = 'MS-DOS'

In [59]:
# columns need to be renamed
dat_dos.rename(columns={'gametitle_mame':'name', 
                        'developer_mame' : 'developer', 
                        'year_mame' : 'release_date', 
                        'genre_mame' : 'genres',
                        'description_mame' : 'summary',
                        'publisher_mame' : 'publisher'}, inplace=True)

In [60]:
# drop ID column
dat_dos = dat_dos.drop(['ID'], axis=1)

In [61]:
dat_dos.head()

,name,developer,release_date,genres,summary,publisher,platform
0,Stunt Island,The Assembly Line,19920101T000000,"Flight Simulator,Vehicle Simulation",Stunt Island was marketed as The Stunt Flying ...,"Walt Disney Computer Software, Inc.",MS-DOS
1,Tommy's Yahtzee,Tommy's Toys,19860101T000000,Board / Party Game,Tommy's Yahtzee is a shareware implementation ...,Freeware,MS-DOS
2,Fantasy Empires,Silicon Knights,19931001T000000,Strategy,Build and control an Empire! In Fantasy Empire...,"Strategic Simulations, Inc.",MS-DOS
3,Pune,Hardware Not Included,19950101T000000,Action,Pune is a light cycle/snake-type game for mult...,Hardware Not Included,MS-DOS
4,Mortal Kombat,Probe Software Ltd.,19940525T000000,"Action,Fighting","Five Hundred years ago, an ancient and well re...","Acclaim Entertainment, Inc.",MS-DOS

In [62]:
duplicates = dat_dos[dat_dos.duplicated(subset=['name', 'platform'], keep=False)].sort_values(['name', 'platform', 'summary', 'developer', 'publisher'])
duplicates.head()

,name,developer,release_date,genres,summary,publisher,platform
1178,Action Fighter,"Softstar Entertainment, Inc.",19940101T000000,"Action,Fighting",A side scrolling beat em' up from Korea.,"Softstar Entertainment, Inc.",MS-DOS
7245,Action Fighter,"Softstar Entertainment, Inc.",19940101T000000,"Action,Fighting",A side scrolling beat em' up from Korea.,"Softstar Entertainment, Inc.",MS-DOS
6151,Action Fighter,Sega Enterprises Ltd.,19890101T000000,"Action,Racing / Driving",This is a top down vertically scrolling shoote...,Firebird Software,MS-DOS
7326,Action Fighter,Sega Enterprises Ltd.,19890101T000000,"Action,Racing / Driving",This is a top down vertically scrolling shoote...,Firebird Software,MS-DOS
5710,Aldo's Assault,Unknown,19910101T000000,"Action,Platform",Aldo's Assault is the third game in the Aldo s...,Freeware,MS-DOS

In [63]:
# sort for duplicate removal such that the non-empty value for each column comes first
dat_dos = dat_dos.sort_values(['name', 'platform', 'summary', 'developer', 'publisher'])

# remove duplicates, keep first
print(len(dat_dos))
dat_dos = dat_dos.drop_duplicates(subset=['name', 'platform'], keep='first').sort_values(['name', 'platform'])
print(len(dat_dos))

7482
7082

In [64]:
# there are some dashes in release_date, replace them with None
dat_dos['release_date'].replace('-', None, inplace=True)

# release_date to datetime
dat_dos['release_date'] = pd.to_datetime(dat_dos['release_date'])

/tmp/ipykernel_37486/470230813.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dat_dos['release_date'].replace('-', None, inplace=True)

In [65]:
# this one was easy. ready for merging
merged_df = pd.merge(merged_df, dat_dos, on=['name', 'platform'], how='outer', validate="many_to_many")

In [66]:
merged_df.head()

,name,release_year,cooperative,platform,rating,user_rating,release_date_x,players,genres_x,developer_x,publisher_x,summary_x,developer_y,release_date_y,genres_y,summary_y,publisher_y
0,! That Bastard Is Trying To Steal Our Gold !,None,0.0,Windows,None,8.0,NaT,NaN,Platform; Puzzle,WTFOMGames,WTFOMGames,Steal gold from the Lerpikon's dungeons! Get r...,NaN,NaT,NaN,NaN,NaN
1,!!!Ants!!!,1979.0,0.0,Tandy TRS-80,None,5.0,NaT,1.0,None,Brian Rotolante,Synergistic Solar Inc.,In Ants you can become an ant and join the ran...,NaN,NaT,NaN,NaN,NaN
2,"""300""",1975.0,0.0,Pinball,None,6.944444,NaT,4.0,Pinball,Gottlieb,Gottlieb,"""300"" (the exact machine name includes the quo...",NaN,NaT,NaN,NaN,NaN
3,"""8 Ball""",1952.0,0.0,Pinball,None,7.25,NaT,2.0,Pinball,Williams Electronic Games,Williams Electronic Games,A pool table themed pinball game from Williams...,NaN,NaT,NaN,NaN,NaN
4,"""History in the Making"": The First Three Years",1988.0,0.0,Amstrad CPC,None,6.972222,NaT,4.0,Compilation,None,U.S. Gold,A celebration of U.S. Gold's first three years...,NaN,NaT,NaN,NaN,NaN

In [67]:
# replace  so the code in the next cell would work
merged_df = merged_df.replace({np.nan : None})

In [68]:
# perform column joins using functions on release_date, genres, developer, publisher and summary
merged_df['release_date'] = merged_df.apply(cj.prioritize_value, args=['release_date_x', 'release_date_y'], axis=1)
merged_df['genres'] = merged_df.apply(cj.join_genres, args=['genres_x', 'genres_y'], axis=1)
merged_df['developer'] = merged_df.apply(cj.prioritize_columns, args=['developer_x', 'developer_y'], axis=1)
merged_df['publisher'] = merged_df.apply(cj.prioritize_columns, args=['publisher_x', 'publisher_y'], axis=1)
merged_df['summary'] = merged_df.apply(cj.prioritize_summary, args=['summary_x', 'summary_y'], axis=1)

In [69]:
# drop user_rating_x, user_rating_y, summary_x, summary_y
merged_df = merged_df.drop(['summary_x','summary_y',
                            'developer_x', 'developer_y',
                            'publisher_x', 'publisher_y',
                            'release_date_x', 'release_date_y',
                            'genres_x', 'genres_y'], axis=1)

In [70]:
merged_df.head()

,name,release_year,cooperative,platform,rating,user_rating,players,release_date,genres,developer,publisher,summary
0,! That Bastard Is Trying To Steal Our Gold !,None,0.0,Windows,None,8.0,None,NaT,Platform; Puzzle,WTFOMGames,WTFOMGames,Steal gold from the Lerpikon's dungeons! Get r...
1,!!!Ants!!!,1979.0,0.0,Tandy TRS-80,None,5.0,1.0,NaT,None,Brian Rotolante,Synergistic Solar Inc.,In Ants you can become an ant and join the ran...
2,"""300""",1975.0,0.0,Pinball,None,6.944444,4.0,NaT,Pinball,Gottlieb,Gottlieb,"""300"" (the exact machine name includes the quo..."
3,"""8 Ball""",1952.0,0.0,Pinball,None,7.25,2.0,NaT,Pinball,Williams Electronic Games,Williams Electronic Games,A pool table themed pinball game from Williams...
4,"""History in the Making"": The First Three Years",1988.0,0.0,Amstrad CPC,None,6.972222,4.0,NaT,Compilation,None,U.S. Gold,A celebration of U.S. Gold's first three years...

## DAT MAME

In [85]:
dat_mame = pd.read_csv('csv/dat_database_mame.csv')

/tmp/ipykernel_37486/828397307.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  dat_mame = pd.read_csv('csv/dat_database_mame.csv')

In [86]:
dat_mame.head()

,ID,systemname_mame,gametitle_mame,filename_mame,cloneof_mame,manufacturer_mame,year_mame,genre_mame
0,355065,advmame 0.94-RetroPie-260.dat,"PuckMan (Japan set 1, Probably Bootleg)",puckman,NaN,Namco,1980/01/01,NaN
1,355066,advmame 0.94-RetroPie-260.dat,PuckMan (Japan set 2),puckmana,puckman,Namco,1980/01/01,NaN
2,355067,advmame 0.94-RetroPie-260.dat,PuckMan (Japan set 1 with speedup hack),puckmanf,puckman,Namco,1980/01/01,NaN
3,355068,advmame 0.94-RetroPie-260.dat,Puckman (Falcom),puckmanh,puckman,hack,1980/01/01,NaN
4,355069,advmame 0.94-RetroPie-260.dat,Pac-Man (Midway),pacman,puckman,[Namco] (Midway license),1980/01/01,NaN

In [87]:
dat_mame.isnull().sum()

ID                        0
systemname_mame           0
gametitle_mame            0
filename_mame             0
cloneof_mame         101633
manufacturer_mame     11907
year_mame             95935
genre_mame           193224
dtype: int64

In [88]:
dat_mame['systemname_mame'].value_counts()

systemname_mame
MAME 0.260.dat                                   46199
MAME 0.240 (Arcade).dat                          36604
mame2016 - MAME 0.174 Arcade XML.dat             32071
mame2015 - MAME 0.160 XML.dat                    30906
Mame 0.239.xml                                   29027
Mame 0.270.xml                                   17538
Mame 0.267.xml                                   12904
mame2010.xml                                      8833
FinalBurn_Neo_ClrMame_Pro_XML_Arcade_only.dat     6998
advmame 12-106.dat                                6166
advmame 0.94-RetroPie-260.dat                     5563
mame2003-plus.xml                                 5219
mame2003.xml                                      4726
vgmplay.xml                                       3645
FB Alpha 2012 v0.2.97.30.dat                      3369
mame2000 mame4all - MAME 0.37b5.dat               2241
FB Alpha v0.2.96.71 working_roms.dat               684
Name: count, dtype: int64

In [89]:
# looks like duplicates for each version of MAME. Let's use the one that says Arcade.
dat_mame_subset = dat_mame[dat_mame['systemname_mame'] == 'MAME 0.240 (Arcade).dat']

In [90]:
dat_mame_subset.head()

,ID,systemname_mame,gametitle_mame,filename_mame,cloneof_mame,manufacturer_mame,year_mame,genre_mame
51807,406872,MAME 0.240 (Arcade).dat,005,005,NaN,Sega,1981/01/01,NaN
51808,406873,MAME 0.240 (Arcade).dat,"100 Lions (10219211, NSW/ACT)",100lions,NaN,Aristocrat,2006/01/01,NaN
51809,406874,MAME 0.240 (Arcade).dat,"10-Yard Fight (World, set 1)",10yard,NaN,Irem,1983/01/01,NaN
51810,406875,MAME 0.240 (Arcade).dat,"10-Yard Fight '85 (US, Taito license)",10yard85,10yard,Irem (Taito license),1985/01/01,NaN
51811,406876,MAME 0.240 (Arcade).dat,10-Yard Fight (Japan),10yardj,10yard,Irem,1983/01/01,NaN

In [91]:
# rename genre to genres
dat_mame_subset.rename(columns={'genre' : 'genres'}, inplace=True)

# only desired columns
dat_mame_subset = dat_mame_subset[['gametitle_mame', 'filename_mame', 'manufacturer_mame', 'year_mame', 'genre_mame']]

# create platform column named Arcade
dat_mame_subset['platform'] = 'Arcade'

# release_date to datetime
dat_mame_subset['year_mame'] = pd.to_datetime(dat_mame_subset['year_mame'])

/tmp/ipykernel_37486/4218908207.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dat_mame_subset.rename(columns={'genre' : 'genres'}, inplace=True)

In [92]:
duplicates = dat_mame_subset[dat_mame_subset.duplicated(subset=['name', 'platform'], keep=False)].sort_values(['name', 'platform', 'developer', 'release_date', 'genres'])
duplicates.head()

KeyError: Index(['name'], dtype='object')

In [ ]:
# sort for duplicate removal such that the non-empty value for each column comes first
dat_mame_subset = dat_mame_subset.sort_values(['name', 'platform', 'developer', 'release_date', 'genres'])

# remove duplicates, keep first
print(len(dat_mame_subset))
dat_mame_subset = dat_mame_subset.drop_duplicates(subset=['name', 'platform'], keep='first').sort_values(['name', 'platform'])
print(len(dat_mame_subset))

36604
36602

In [ ]:
# merging
merged_df = pd.merge(merged_df, dat_mame_subset, on=['name', 'platform'], how='outer', validate="many_to_many")

In [ ]:
merged_df = merged_df.replace({np.nan : None})

# column join functions for release_date, developer and genres
merged_df['release_date'] = merged_df.apply(cj.prioritize_value, args=['release_date_x', 'release_date_y'], axis=1)
merged_df['developer'] = merged_df.apply(cj.prioritize_columns, args=['developer_x', 'developer_y'], axis=1)
merged_df['genres'] = merged_df.apply(cj.join_genres, args=['genres_x', 'genres_y'], axis=1)

# drop processed columns
merged_df = merged_df.drop(['developer_x', 'developer_y',
                            'genres_x', 'genres_y',
                            'release_date_x', 'release_date_y'], axis=1)

In [ ]:
merged_df.head()

,name,release_year,cooperative,platform,rating,user_rating,players,publisher,summary,filename,release_date,developer,genres
0,20th Century Video Almanac,1993.0,0.0,3DO Interactive Multiplayer,None,6.559701,1.0,The Software Toolworks,"In The Best of Our Century, we've taken multim...",None,NaT,The Software Toolworks,Education
1,3D Atlas,1994.0,0.0,3DO Interactive Multiplayer,None,7.0,1.0,Electronic Arts,The World Isn't Flat. Why Should Your Atlas Be...,None,NaT,Electronic Arts,Education
2,3DO Action Pak,1995.0,0.0,3DO Interactive Multiplayer,None,7.413333,1.0,3DO,This is a four-game compilation pack that cont...,None,NaT,3DO,Action
3,3DO de Shiru Miru Asobu Nakajima Miyuki,None,0.0,3DO Interactive Multiplayer,None,7.333333,1.0,Pony Canyon,None,None,NaT,None,None
4,3DO Demo Disc Program,None,0.0,3DO Interactive Multiplayer,None,6.745455,None,None,A white binder with blue silk-screened art. Th...,None,NaT,None,None

### Recalbox

In [ ]:
recalbox = pd.read_csv('csv/recalbox_gamelist.csv')
recalbox_xml = pd.read_csv('csv/recalbox_gamelist_xml.csv')

In [ ]:
recalbox.columns

Index(['numauto_rom', 'nomjeu_rom', 'fichier_rom', 'description_rom',
       'image_rom', 'rating_rom', 'annee_rom', 'developer_rom',
       'publisher_rom', 'genre_rom', 'players_rom', 'cache_rom', 'favoris_rom',
       'boxart_rom', 'screenshot_rom', 'wheel_rom', 'video_rom', 'mix_rom',
       'playcount_rom', 'lastplayed_rom', 'md5_rom', 'core_rom',
       'emulator_rom', 'cartridge_rom', 'hash_rom', 'manual_rom', 'region_rom',
       'thumbnail_rom', 'marquee_rom', 'genreid_rom', 'fanart_rom', 'map_rom',
       'titleshot_rom', 'lang_rom', 'gameid_rom', 'kid_rom', 'adult_rom',
       'arcadesystemname_rom', 'gametime_rom', 'boxback_rom', 'temporary_rom',
       'bezel_rom', 'ratio_rom', 'rotation_rom', 'extra1_rom', 'famille_rom',
       'mode_rom'],
      dtype='object')

In [ ]:
# checking if ready for concatenation
recalbox_xml.columns == recalbox.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
# append dataframes
recalbox = pd.concat([recalbox, recalbox_xml])

In [ ]:
recalbox.head()

,numauto_rom,nomjeu_rom,fichier_rom,description_rom,image_rom,rating_rom,annee_rom,developer_rom,publisher_rom,genre_rom,...,arcadesystemname_rom,gametime_rom,boxback_rom,temporary_rom,bezel_rom,ratio_rom,rotation_rom,extra1_rom,famille_rom,mode_rom
0,17605,10000000-in-1 [p1][!],./10000000-in-1 [p1][!].zip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17606,10-Yard Fight,./10-Yard Fight (U).zip,10-Yard Fight is a simple arcade game based on...,./miximages/10-Yard Fight (U).png,0.4,19851206T000000,Irem,Nintendo,Sports,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17607,10-Yard Fight,./10-Yard Fight.zip,10-Yard Fight is a simple arcade game based on...,./miximages/10-Yard Fight.png,0.4,19851206T000000,Irem,Nintendo,Sports,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17608,118-in-1 [p1][!],./118-in-1 [p1][!].zip,NaN,./miximages/118-in-1 [p1][!].png,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17609,11-in-1 Ball Games [p1][!],./11-in-1 Ball Games [p1][!].zip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# keep only those columns
recalbox = recalbox.iloc[:, 1:11]

# drop image column
recalbox = recalbox.drop(['image_rom'], axis=1)

In [ ]:
recalbox.rename(columns={'nomjeu_rom':'name', 
                         'fichier_rom':'filename',
                         'description_rom':'summary', 
                         'rating_rom':'user_rating', 
                         'annee_rom':'release_date',
                         'developer_rom':'developer', 
                         'publisher_rom':'publisher',
                         'genre_rom':'genres', 
                         'players_rom':'players'}, inplace=True)

In [ ]:
recalbox['platform'] = 'Nintendo Entertainment System'

# release_date to datetime
recalbox['release_date'] = pd.to_datetime(recalbox['release_date'])

# deal w nans
recalbox = recalbox.replace({np.nan : None})

In [ ]:
duplicates = recalbox[recalbox.duplicated(subset=['name', 'filename'], keep=False)].sort_values(['name', 'filename', 'summary', 'developer', 'publisher'])
duplicates.head()

,name,filename,summary,user_rating,release_date,developer,publisher,genres,players,platform
1,10-Yard Fight,./10-Yard Fight (U).zip,10-Yard Fight is a simple arcade game based on...,0.4,1985-12-06 00:00:00,Irem,Nintendo,Sports,1-2,Nintendo Entertainment System
2,10-Yard Fight,./10-Yard Fight (U).zip,10-Yard Fight is a simple arcade game based on...,0.4,1985-12-06 00:00:00,Irem,Nintendo,Sports,1-2,Nintendo Entertainment System
2,10-Yard Fight,./10-Yard Fight.zip,10-Yard Fight is a simple arcade game based on...,0.4,1985-12-06 00:00:00,Irem,Nintendo,Sports,1-2,Nintendo Entertainment System
1,10-Yard Fight,./10-Yard Fight.zip,10-Yard Fight is a simple arcade game based on...,0.4,1985-12-06 00:00:00,Irem,Nintendo,Sports,1-2,Nintendo Entertainment System
3,118-in-1 [p1][!],./118-in-1 [p1][!].zip,None,None,None,None,None,None,None,Nintendo Entertainment System

In [ ]:
# sort for duplicate removal such that the non-empty value for each column comes first
recalbox = recalbox.sort_values(['name', 'filename', 'summary', 'developer', 'publisher'])

# remove duplicates, keep first
print(len(recalbox))
recalbox = recalbox.drop_duplicates(subset=['name'], keep='first').sort_values(['name', 'platform'])
print(len(recalbox))

3990
1545

In [ ]:
# code for formatting players values to our standard
def extract_max_players(players):
    if players is None:
        return None
    if '-' in str(players):
        return int(players.split('-')[-1])  # Extract the maximum number of players after splitting by '-'
    else:
        return int(players)  # If it's already a single value, return it as an integer

In [ ]:
recalbox['players'] = recalbox['players'].apply(extract_max_players)

In [ ]:
# user rating is 0-1 so multiply by 10 so it'd be bevt 1-10
recalbox['user_rating'] = recalbox['user_rating'] * 10

In [ ]:
recalbox.head()

,name,filename,summary,user_rating,release_date,developer,publisher,genres,players,platform
1,10-Yard Fight,./10-Yard Fight (U).zip,10-Yard Fight is a simple arcade game based on...,4.0,1985-12-06 00:00:00,Irem,Nintendo,Sports,2.0,Nintendo Entertainment System
0,10000000-in-1 [p1][!],./10000000-in-1 [p1][!].zip,None,NaN,None,None,None,None,NaN,Nintendo Entertainment System
4,11-in-1 Ball Games [p1][!],./11-in-1 Ball Games [p1][!].zip,None,NaN,None,None,None,None,NaN,Nintendo Entertainment System
3,118-in-1 [p1][!],./118-in-1 [p1][!].zip,None,NaN,None,None,None,None,NaN,Nintendo Entertainment System
5,150-in-1 (Mapper 202) [p1][!],./150-in-1 (Mapper 202) [p1][!].zip,None,NaN,None,None,None,None,NaN,Nintendo Entertainment System

In [ ]:
# merging
merged_df = pd.merge(merged_df, recalbox, on=['name', 'platform'], how='outer', validate="many_to_many")

In [ ]:
merged_df.head()

,name,release_year,cooperative,platform,rating,user_rating_x,players_x,publisher_x,summary_x,filename_x,...,developer_x,genres_x,filename_y,summary_y,user_rating_y,release_date_y,developer_y,publisher_y,genres_y,players_y
0,20th Century Video Almanac,1993.0,0.0,3DO Interactive Multiplayer,None,6.559701,1.0,The Software Toolworks,"In The Best of Our Century, we've taken multim...",None,...,The Software Toolworks,Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3D Atlas,1994.0,0.0,3DO Interactive Multiplayer,None,7.0,1.0,Electronic Arts,The World Isn't Flat. Why Should Your Atlas Be...,None,...,Electronic Arts,Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3DO Action Pak,1995.0,0.0,3DO Interactive Multiplayer,None,7.413333,1.0,3DO,This is a four-game compilation pack that cont...,None,...,3DO,Action,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3DO de Shiru Miru Asobu Nakajima Miyuki,None,0.0,3DO Interactive Multiplayer,None,7.333333,1.0,Pony Canyon,None,None,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3DO Demo Disc Program,None,0.0,3DO Interactive Multiplayer,None,6.745455,None,None,A white binder with blue silk-screened art. Th...,None,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
merged_df = merged_df.replace({np.nan : None})

In [ ]:
# column join functions for rating, players, publisher, developer, summary, release_date
merged_df['user_rating'] = merged_df.apply(cj.prioritize_columns, args=['user_rating_x', 'user_rating_y'], axis=1)
merged_df['players'] = merged_df.apply(cj.prioritize_value, args=['players_x', 'players_y'], axis=1)
merged_df['publisher'] = merged_df.apply(cj.prioritize_columns, args=['publisher_x', 'publisher_y'], axis=1)
merged_df['developer'] = merged_df.apply(cj.prioritize_columns, args=['developer_x', 'developer_y'], axis=1)
merged_df['summary'] = merged_df.apply(cj.prioritize_summary, args=['summary_x', 'summary_y'], axis=1)
merged_df['release_date'] = merged_df.apply(cj.prioritize_value, args=['release_date_x', 'release_date_y'], axis=1)
merged_df['filename'] = merged_df.apply(cj.prioritize_columns, args=['filename_x', 'filename_y'], axis=1)
merged_df['genres'] = merged_df.apply(cj.join_genres, args=['genres_x', 'genres_y'], axis=1)

In [ ]:
# drop processed columns
merged_df = merged_df.drop(['developer_x', 'developer_y',
                            'publisher_x', 'publisher_y',
                            'release_date_x', 'release_date_y',
                            'genres_x', 'genres_y',
                            'filename_x', 'filename_y',
                            'user_rating_x', 'user_rating_y',
                            'players_x', 'players_y',
                            'summary_x', 'summary_y'], axis=1)

In [ ]:
# drop duplicates
merged_df = merged_df.drop_duplicates()

In [ ]:
merged_df.head()

,name,release_year,cooperative,platform,rating,user_rating,players,publisher,developer,summary,release_date,filename,genres
0,20th Century Video Almanac,1993.0,0.0,3DO Interactive Multiplayer,None,6.559701,1.0,The Software Toolworks,The Software Toolworks,"In The Best of Our Century, we've taken multim...",NaT,None,Education
1,3D Atlas,1994.0,0.0,3DO Interactive Multiplayer,None,7.0,1.0,Electronic Arts,Electronic Arts,The World Isn't Flat. Why Should Your Atlas Be...,NaT,None,Education
2,3DO Action Pak,1995.0,0.0,3DO Interactive Multiplayer,None,7.413333,1.0,3DO,3DO,This is a four-game compilation pack that cont...,NaT,None,Action
3,3DO de Shiru Miru Asobu Nakajima Miyuki,None,0.0,3DO Interactive Multiplayer,None,7.333333,1.0,Pony Canyon,None,None,NaT,None,None
4,3DO Demo Disc Program,None,0.0,3DO Interactive Multiplayer,None,6.745455,NaN,None,None,A white binder with blue silk-screened art. Th...,NaT,None,None

In [ ]:
import pickle
with open('merged_df.pkl', 'wb') as f:
    pickle.dump(merged_df, f)