## Data Preparation

In [1]:
import pickle
from data_cleaning import run_cleaning_pipeline

In [2]:
# load merged_df.pkl
with open('merged_df.pkl', 'rb') as f:
    merged_df = pickle.load(f)

In [3]:
merged_df.head()

,name,platform,filename,summary,release_date,release_year,genres,developer,publisher,players,cooperative,rating,user_rating
0,! That Bastard Is Trying To Steal Our Gold !,Windows,NaN,Steal gold from the Lerpikon's dungeons! Get r...,NaT,<NA>,"Platform, Puzzle",WTFOMGames,WTFOMGames,<NA>,False,NaN,8.000000
1,!!!Ants!!!,Tandy TRS-80,NaN,In Ants you can become an ant and join the ran...,NaT,1979,NaN,Brian Rotolante,Synergistic Solar Inc.,1,False,NaN,5.000000
2,"""300""",Pinball,NaN,"""300"" (the exact machine name includes the quo...",NaT,1975,Pinball,Gottlieb,Gottlieb,4,False,NaN,6.944444
3,"""8 Ball""",Pinball,NaN,A pool table themed pinball game from Williams...,NaT,1952,Pinball,Williams Electronic Games,Williams Electronic Games,2,False,NaN,7.250000
4,"""History in the Making"": The First Three Years",Amstrad CPC,NaN,A celebration of U.S. Gold's first three years...,NaT,1988,Compilation,NaN,U.S. Gold,4,False,NaN,6.972222

### Portuguese genres

In [4]:
# Portuguese to English genre translation map based on recalbox['genre_rom'].unique()
portuguese_genre_map = {
    # Core genres
    'Ação': 'Action',
    'Plataforma': 'Platform',
    'Quebra-Cabeças': 'Puzzle',
    'Quebra-cabeças': 'Puzzle',
    'Esporte': 'Sports',
    'Aventura': 'Adventure',
    'Luta': 'Fighting',
    'Briga De Rua': "Beat'em Up",
    'Briga de rua': "Beat'em Up",
    'Estratégia': 'Strategy',
    'Simulação': 'Simulation',
    'Corrida, Pilotagem': 'Racing',
    'Jogos De Rpg': 'Role Playing Game',
    'Jogos de RPG': 'Role Playing Game',
    'Tiro': 'Shooter',
    'Pinball': 'Pinball',
    'Educacional': 'Educational',
    'Variados': 'Various',
    'Cassino': 'Casino',
    
    # Compound terms
    'Jogo de tabuleiro': 'Board Game',
    'Jogo De Tabuleiro': 'Board Game',
    'Cartas': 'Cards',
    'Corrida Em 3ª Pessoa': 'Racing (Third Person)',
    'Tiro Com Acessórios': 'Light Gun Shooter',
    
    # Platform subtypes
    'Plataforma / Combate Com Rolagem': 'Platform / Fighter Scrolling',
    'Plataforma / Combate com rolagem': 'Platform / Fighter Scrolling',
    'Plataforma / Corre E Pula': 'Platform / Run & Jump',
    'Plataforma / Corre E Pula Com Rolagem': 'Platform / Run & Jump Scrolling',
    'Combate Com Rolagem': 'Fighter Scrolling',
    'Combate com rolagem': 'Fighter Scrolling',
    'Corre E Pula': 'Run & Jump',
    'Corre E Pula Com Rolagem': 'Run & Jump Scrolling',
    
    # Action subtypes
    'Ação / Aventura': 'Action / Adventure',
    
    # Sports subtypes
    'Esporte / Futebol': 'Sports / Football (Soccer)',
    'Esporte / Basquete': 'Sports / Basketball',
    'Esporte / Tênis': 'Sports / Tennis',
    'Esporte / Futebol Americano': 'Sports / Football (American)',
    'Esporte / Golfe': 'Sports / Golf',
    'Esporte / Boxe': 'Sports / Boxing',
    'Esporte / Luta Livre': 'Sports / Wrestling',
    'Basquete': 'Basketball',
    'Tênis': 'Tennis',
    'Futebol': 'Football (Soccer)',
    'Futebol Americano': 'Football (American)',
    'Golfe': 'Golf',
    'Boxe': 'Boxing',
    'Luta Livre': 'Wrestling',
}

print(f"Translation map contains {len(portuguese_genre_map)} mappings")

Translation map contains 47 mappings

### Main cleaning

In [5]:
cleaned_df = run_cleaning_pipeline(merged_df, genre_translation_map=portuguese_genre_map)

In [6]:
cleaned_df.head()

,name,platform,filename,summary,release_date,release_year,genres,developer,publisher,players,cooperative,rating,user_rating
0,! That Bastard Is Trying To Steal Our Gold !,Windows,NaN,Steal gold from the Lerpikon's dungeons! Get r...,NaN,<NA>,"Platform, Puzzle",WTFOMGames,WTFOMGames,<NA>,False,NaN,8.00
1,!!!Ants!!!,Tandy TRS-80,NaN,In Ants you can become an ant and join the ran...,NaN,1979,NaN,Brian Rotolante,Synergistic Solar Inc.,1,False,NaN,5.00
2,"""300""",Pinball,NaN,"""300"" (the exact machine name includes the quo...",NaN,1975,Pinball,Gottlieb,Gottlieb,4,False,NaN,6.94
3,"""8 Ball""",Pinball,NaN,A pool table themed pinball game from Williams...,NaN,1952,Pinball,Williams Electronic Games,Williams Electronic Games,2,False,NaN,7.25
4,"""History in the Making"": The First Three Years",Amstrad CPC,NaN,A celebration of U.S. Gold's first three years...,NaN,1988,Compilation,NaN,U.S. Gold,4,False,NaN,6.97