# 06 - Update Games

Scan ROM folders, match against a video game metadata dataset, and build/update `gamelist.xml` files.

**Pipeline overview:**
1. Scan game folders to build an inventory of owned ROMs
2. Load a cleaned metadata dataset (`.pkl`)
3. Build or update `gamelist.xml` files using one of three source modes:
   - `files_only` — inventory from ROM files on disk
   - `xml_only` — inventory from an existing `gamelist.xml`
   - `both` — merge both sources (XML entries take priority, new files are appended)

In [1]:
from pathlib import Path
import pandas as pd

from utils.game_parser import scan_platform_folder, scan_games_folders

In [2]:
# Create a small test ROM tree
test_root = Path('/mnt/anaconda/games')
(test_root / 'nes').mkdir(parents=True, exist_ok=True)
(test_root / 'psx').mkdir(parents=True, exist_ok=True)

# sample_files = [
#     test_root / 'nes' / 'Super Mario Bros (USA).nes',
#     test_root / 'nes' / 'Contra [!].zip',
#     test_root / 'psx' / 'Metal Gear Solid (USA).cue',
#     test_root / 'psx' / 'Metal Gear Solid (USA).bin',
#     test_root / 'psx' / 'Readme.txt',
# ]

# for file_path in sample_files:
#     file_path.touch(exist_ok=True)

# print(f'Test files created in: {test_root.resolve()}')

In [3]:
# 1) Scan one platform folder (NES)
nes_df = scan_platform_folder(test_root / 'nes')
print('NES scan:')
display(nes_df)

# 2) Scan all platform folders under root (non-strict: all files are treated as games)
all_df = scan_games_folders(test_root, strict_extensions=False)
print('All platforms (strict_extensions=False):')
display(all_df)

# 3) Strict scan using platform formats
all_strict_df = scan_games_folders(test_root, strict_extensions=True)
print('All platforms (strict_extensions=True):')
display(all_strict_df)

print('Rows (non-strict):', len(all_df))
print('Rows (strict):', len(all_strict_df))

NES scan:

,name,filename,platform,platform_key,source_path,extension
0,Trojan,Trojan (USA).zip,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/Trojan (USA).zip,.zip
1,Mad Max,Mad Max (USA).zip,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/Mad Max (USA).zip,.zip
2,Pictionary - The Game of Video Quick Draw,Pictionary - The Game of Video Quick Draw (USA...,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/Pictionary - The Game ...,.zip
3,1991 Du Ma Racing,1991 Du Ma Racing (Asia) (Unl).zip,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/1991 Du Ma Racing (Asi...,.zip
4,Fatal Fury 2,Fatal Fury 2 (Unl).zip,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/Fatal Fury 2 (Unl).zip,.zip
...,...,...,...,...,...,...
2545,Best of the Best - Championship Karate,Best of the Best - Championship Karate (U).png,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/miximages/Best of the ...,.png
2546,Super Jeopardy!,Super Jeopardy! (U).png,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/miximages/Super Jeopar...,.png
2547,Thunderbirds,Thunderbirds (U).png,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/miximages/Thunderbirds...,.png
2548,Pegasus 4 in 1,Pegasus 4 in 1 (Unknown) (Unl).png,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/miximages/Pegasus 4 in...,.png
2549,Bugs Bunny Fun House,Bugs Bunny Fun House (Prototype) (U).png,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/miximages/Bugs Bunny F...,.png

All platforms (strict_extensions=False):

,name,filename,platform,platform_key,source_path,extension
0,Trojan,Trojan (USA).zip,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/Trojan (USA).zip,.zip
1,Mad Max,Mad Max (USA).zip,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/Mad Max (USA).zip,.zip
2,Pictionary - The Game of Video Quick Draw,Pictionary - The Game of Video Quick Draw (USA...,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/Pictionary - The Game ...,.zip
3,1991 Du Ma Racing,1991 Du Ma Racing (Asia) (Unl).zip,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/1991 Du Ma Racing (Asi...,.zip
4,Fatal Fury 2,Fatal Fury 2 (Unl).zip,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/Fatal Fury 2 (Unl).zip,.zip
...,...,...,...,...,...,...
30142,telix322,telix322.zip,MS-DOS,pc,/mnt/anaconda/games/pc/software/tools/telix322...,.zip
30143,printmas,printmas.zip,MS-DOS,pc,/mnt/anaconda/games/pc/software/tools/printmas...,.zip
30144,pv,pv.zip,MS-DOS,pc,/mnt/anaconda/games/pc/software/tools/pv.zip,.zip
30145,dhive12,dhive12.zip,MS-DOS,pc,/mnt/anaconda/games/pc/software/tools/dhive12.zip,.zip
30146,list,list.rar,MS-DOS,pc,/mnt/anaconda/games/pc/software/tools/list.rar,.rar

All platforms (strict_extensions=True):

,name,filename,platform,platform_key,source_path,extension
0,Trojan,Trojan (USA).zip,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/Trojan (USA).zip,.zip
1,Mad Max,Mad Max (USA).zip,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/Mad Max (USA).zip,.zip
2,Pictionary - The Game of Video Quick Draw,Pictionary - The Game of Video Quick Draw (USA...,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/Pictionary - The Game ...,.zip
3,1991 Du Ma Racing,1991 Du Ma Racing (Asia) (Unl).zip,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/1991 Du Ma Racing (Asi...,.zip
4,Fatal Fury 2,Fatal Fury 2 (Unl).zip,Nintendo Entertainment System,nes,/mnt/anaconda/games/nes/Fatal Fury 2 (Unl).zip,.zip
...,...,...,...,...,...,...
18027,pictview,pictview.zip,MS-DOS,pc,/mnt/anaconda/games/pc/software/tools/pictview...,.zip
18028,telix322,telix322.zip,MS-DOS,pc,/mnt/anaconda/games/pc/software/tools/telix322...,.zip
18029,printmas,printmas.zip,MS-DOS,pc,/mnt/anaconda/games/pc/software/tools/printmas...,.zip
18030,pv,pv.zip,MS-DOS,pc,/mnt/anaconda/games/pc/software/tools/pv.zip,.zip
18031,dhive12,dhive12.zip,MS-DOS,pc,/mnt/anaconda/games/pc/software/tools/dhive12.zip,.zip

Rows (non-strict): 30147
Rows (strict): 18032

## Build / Update `gamelist.xml` — unified pipeline

Test the new `build_platform_gamelist()` with each source mode (`files_only`, `xml_only`, `both`) and the multi-platform `build_all_gamelists()` runner.

In [4]:
from utils.gamelist_builder import build_platform_gamelist, build_all_gamelists, load_metadata

# --- Single platform: files_only (no metadata enrichment) ---
result_files = build_platform_gamelist(
    test_root / 'nes',
    output_path=Path('output/test_games/nes/gamelist_files_only.xml'),
    source='files_only',
)
print(result_files)

============================================================
PLATFORM: nes -> Nintendo Entertainment System
  source=files_only  strict_extensions=True
============================================================
  File inventory: 1290 entries
  Combined inventory: 1290 entries
  Written: output/test_games/nes/gamelist_files_only.xml

============================================================
AUDIT REPORT: Nintendo Entertainment System
============================================================
Total games in gamelist.xml: 1290
Matched to metadata: 0 (0.0%)
Unmatched: 1290
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Trojan
  Mad Max
  Pictionary - The Game of Video Quick Draw
  1991 Du Ma Racing
  Fatal Fury 2
============================================================


In [5]:
# --- Single platform: xml_only (uses existing gamelist.xml in the folder) ---
# This requires a gamelist.xml to already exist in the platform folder.
# We'll use the lists/ folder which has gamelist.xml files.
result_xml = build_platform_gamelist(
    Path('lists/nes'),
    output_path=Path('output/test_games/nes/gamelist_xml_only.xml'),
    source='xml_only',
)
print(result_xml)

============================================================
PLATFORM: nes -> Nintendo Entertainment System
  source=xml_only  strict_extensions=True
============================================================
  XML inventory: 1184 entries
  Combined inventory: 1184 entries
  Written: output/test_games/nes/gamelist_xml_only.xml

============================================================
AUDIT REPORT: Nintendo Entertainment System
============================================================
Total games in gamelist.xml: 1184
Matched to metadata: 0 (0.0%)
Unmatched: 1184
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  118-in-1 [p1][!]
  10-Yard Fight
  1943 : The Battle of Midway
  1991 Du Ma Racing
  1999 - Hore, Mita Koto Ka! Seikimatsu
============================================================


In [6]:
# --- Single platform: both (merge XML + file scan) ---
# The test_root games folder is read-only, so we stage a test folder
# with both a gamelist.xml and some ROM files.
import shutil

both_test = Path('output/test_games/nes_both')
both_test.mkdir(parents=True, exist_ok=True)

# Copy a few ROMs from the scanner results
for _, row in nes_df.head(5).iterrows():
    src = Path(row['source_path'])
    dst = both_test / src.name
    if src.exists() and not dst.exists():
        shutil.copy2(src, dst)

# Copy an existing gamelist.xml into the same folder
gamelist_src = Path('lists/nes/gamelist.xml')
if gamelist_src.exists():
    shutil.copy2(gamelist_src, both_test / 'gamelist.xml')

result_both = build_platform_gamelist(
    both_test,
    output_path=Path('output/test_games/nes_both/gamelist_updated.xml'),
    source='both',
)
print(result_both)

============================================================
PLATFORM: nes_both -> nes_both
  source=both  strict_extensions=True
============================================================
  XML inventory: 1184 entries
  File inventory: 6 entries
  Combined inventory: 1185 entries
  Written: output/test_games/nes_both/gamelist_updated.xml

============================================================
AUDIT REPORT: nes_both
============================================================
Total games in gamelist.xml: 1185
Matched to metadata: 0 (0.0%)
Unmatched: 1185
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  118-in-1 [p1][!]
  10-Yard Fight
  1943 : The Battle of Midway
  1991 Du Ma Racing
  1999 - Hore, Mita Koto Ka! Seikimatsu
============================================================


In [7]:
# --- Multi-platform runner: process all subfolders under games root ---
results = build_all_gamelists(
    test_root,
    output_root=Path('output/test_games'),
    source='files_only',
)
for r in results:
    print(f"  {r.get('platform_key')}: inventory={r.get('inventory_count')} matched={r.get('matched_count')}")

============================================================
PLATFORM: amiga -> Commodore Amiga
  source=files_only  strict_extensions=True
============================================================
  File inventory: 154 entries
  Combined inventory: 154 entries
  Written: output/test_games/amiga/gamelist_updated.xml

============================================================
AUDIT REPORT: Commodore Amiga
============================================================
Total games in gamelist.xml: 154
Matched to metadata: 0 (0.0%)
Unmatched: 154
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Worms v1 0 2MB 0230
  InternationalKarate+ v1 5 2063
  AbandonedPlaces2 v2 0
  AbandonedPlaces v1 3 1000
  Turrican2 v1 5 0029
============================================================


============================================================
PLATFORM: atari2600 -> Atari 2600
  source=files_only  strict_extensions=True
============================================================
  File inventory: 822 entries
  Combined inventory: 822 entries
  Written: output/test_games/atari2600/gamelist_updated.xml

============================================================
AUDIT REPORT: Atari 2600
============================================================
Total games in gamelist.xml: 822
Matched to metadata: 0 (0.0%)
Unmatched: 822
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Fun With Numbers
  Othello
  G I Joe - Cobra Strike
  McDonalds
  Dancing Plate
============================================================


============================================================
PLATFORM: bios -> bios
  source=files_only  strict_extensions=True
============================================================
  File inventory: 821 entries
  Combined inventory: 821 entries
  Written: output/test_games/bios/gamelist_updated.xml

============================================================
AUDIT REPORT: bios
============================================================
Total games in gamelist.xml: 821
Matched to metadata: 0 (0.0%)
Unmatched: 821
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  st010 data
  sp1 jipan
  32X S BIOS
  pcfxbios
  sp-45
============================================================


============================================================
PLATFORM: c64 -> Commodore 64
  source=files_only  strict_extensions=True
============================================================
  File inventory: 6000 entries
  Combined inventory: 6000 entries
  Written: output/test_games/c64/gamelist_updated.xml

============================================================
AUDIT REPORT: Commodore 64
============================================================
Total games in gamelist.xml: 6000
Matched to metadata: 0 (0.0%)
Unmatched: 6000
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  nythyhel
  Championship Wrestling copy2 Epyx
  Zamczysko Marex Sonic
  Thing Bounces Back Gremlin
  Mystery Magna Media +4-AFL
============================================================


============================================================
PLATFORM: doom -> MS-DOS
  source=files_only  strict_extensions=True
============================================================
  File inventory: 6 entries
  Combined inventory: 6 entries
  Written: output/test_games/doom/gamelist_updated.xml

============================================================
AUDIT REPORT: MS-DOS
============================================================
Total games in gamelist.xml: 6
Matched to metadata: 0 (0.0%)
Unmatched: 6
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  doom1
  doom2
  HERETIC
  HEXEN
  doom
============================================================


============================================================
PLATFORM: dreamcast -> Sega Dreamcast
  source=files_only  strict_extensions=True
============================================================
  File inventory: 13 entries
  Combined inventory: 13 entries
  Written: output/test_games/dreamcast/gamelist_updated.xml

============================================================
AUDIT REPORT: Sega Dreamcast
============================================================
Total games in gamelist.xml: 13
Matched to metadata: 0 (0.0%)
Unmatched: 13
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Omikron - The Nomad Soul
  Gunbird 2
  NFL 2K1
  Ikaruga
  Soulcalibur
============================================================


============================================================
PLATFORM: fba -> Arcade
  source=files_only  strict_extensions=True
============================================================
  File inventory: 985 entries
  Combined inventory: 985 entries
  Written: output/test_games/fba/gamelist_updated.xml

============================================================
AUDIT REPORT: Arcade
============================================================
Total games in gamelist.xml: 985
Matched to metadata: 0 (0.0%)
Unmatched: 985
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  yiear
  dsmbl
  silentd
  wh1
  sdodgeb
============================================================


============================================================
PLATFORM: fbneo -> Arcade
  source=files_only  strict_extensions=True
============================================================
  File inventory: 211 entries
  Combined inventory: 211 entries
  Written: output/test_games/fbneo/gamelist_updated.xml

============================================================
AUDIT REPORT: Arcade
============================================================
Total games in gamelist.xml: 211
Matched to metadata: 0 (0.0%)
Unmatched: 211
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  1943kai
  killbld
  dino
  thndrx2
  kbash2
============================================================


============================================================
PLATFORM: gba -> Nintendo Game Boy Advance
  source=files_only  strict_extensions=True
============================================================
  File inventory: 1211 entries
  Combined inventory: 1211 entries
  Written: output/test_games/gba/gamelist_updated.xml

============================================================
AUDIT REPORT: Nintendo Game Boy Advance
============================================================
Total games in gamelist.xml: 1211
Matched to metadata: 0 (0.0%)
Unmatched: 1211
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Adventures of Jimmy Neutron Boy Genius vs Jimmy Negatron, The
  Madden NFL 07
  Midway's Greatest Arcade Hits
  Super Mario Advance 4 - Super Mario Bros 3
  Bomberman Max 2 - Red Advance
============================================================


============================================================
PLATFORM: mame -> Arcade
  source=files_only  strict_extensions=True
============================================================
  File inventory: 1936 entries
  Combined inventory: 1936 entries
  Written: output/test_games/mame/gamelist_updated.xml

============================================================
AUDIT REPORT: Arcade
============================================================
Total games in gamelist.xml: 1936
Matched to metadata: 0 (0.0%)
Unmatched: 1936
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  yiear
  sflush
  sslam
  zigzagb
  cclimber
============================================================


============================================================
PLATFORM: mastersystem -> Sega Master System
  source=files_only  strict_extensions=True
============================================================
  File inventory: 420 entries
  Combined inventory: 420 entries
  Written: output/test_games/mastersystem/gamelist_updated.xml

============================================================
AUDIT REPORT: Sega Master System
============================================================
Total games in gamelist.xml: 420
Matched to metadata: 0 (0.0%)
Unmatched: 420
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Monica no Castelo do Dragao
  Alex Kidd in Miracle World
  After Burner
  Sonic Chaos
  Trans-Bot
============================================================


============================================================
PLATFORM: megadrive -> Sega Mega Drive
  source=files_only  strict_extensions=True
============================================================
  File inventory: 1083 entries
  Combined inventory: 1083 entries
  Written: output/test_games/megadrive/gamelist_updated.xml

============================================================
AUDIT REPORT: Sega Mega Drive
============================================================
Total games in gamelist.xml: 1083
Matched to metadata: 0 (0.0%)
Unmatched: 1083
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Ooze
  Mystical Fighter
  Dynamite Duke
  Gunship
  Addams Family Values
============================================================


============================================================
PLATFORM: n64 -> Nintendo 64
  source=files_only  strict_extensions=True
============================================================
  File inventory: 217 entries
  Combined inventory: 217 entries
  Written: output/test_games/n64/gamelist_updated.xml

============================================================
AUDIT REPORT: Nintendo 64
============================================================
Total games in gamelist.xml: 217
Matched to metadata: 0 (0.0%)
Unmatched: 217
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Mickey's Speedway USA
  California Speed
  S C A R S
  SUPER MARIO 64
  Bomberman 64
============================================================


============================================================
PLATFORM: neogeo -> SNK Neo Geo
  source=files_only  strict_extensions=True
============================================================
  File inventory: 205 entries
  Combined inventory: 205 entries
  Written: output/test_games/neogeo/gamelist_updated.xml

============================================================
AUDIT REPORT: SNK Neo Geo
============================================================
Total games in gamelist.xml: 205
Matched to metadata: 0 (0.0%)
Unmatched: 205
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  wh1
  sdodgeb
  dragonsh
  ms5plus
  gururin
============================================================


============================================================
PLATFORM: nes -> Nintendo Entertainment System
  source=files_only  strict_extensions=True
============================================================
  File inventory: 1290 entries
  Combined inventory: 1290 entries
  Written: output/test_games/nes/gamelist_updated.xml

============================================================
AUDIT REPORT: Nintendo Entertainment System
============================================================
Total games in gamelist.xml: 1290
Matched to metadata: 0 (0.0%)
Unmatched: 1290
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Trojan
  Mad Max
  Pictionary - The Game of Video Quick Draw
  1991 Du Ma Racing
  Fatal Fury 2
============================================================


============================================================
PLATFORM: pc -> MS-DOS
  source=files_only  strict_extensions=True
============================================================
  File inventory: 269 entries
  Combined inventory: 269 entries
  Written: output/test_games/pc/gamelist_updated.xml

============================================================
AUDIT REPORT: MS-DOS
============================================================
Total games in gamelist.xml: 269
Matched to metadata: 0 (0.0%)
Unmatched: 269
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Commander Keen
  gobliiins
  Lode Runner
  abuse
  Dungeon Keeper
============================================================


============================================================
PLATFORM: pcengine -> NEC PC Engine
  source=files_only  strict_extensions=True
============================================================
  File inventory: 346 entries
  Combined inventory: 346 entries
  Written: output/test_games/pcengine/gamelist_updated.xml

============================================================
AUDIT REPORT: NEC PC Engine
============================================================
Total games in gamelist.xml: 346
Matched to metadata: 0 (0.0%)
Unmatched: 346
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Mahjong Gokuu Special
  Volfied
  Hatris
  Psycho Chaser
  Heavy Unit
============================================================


============================================================
PLATFORM: ports -> ports
  source=files_only  strict_extensions=True
============================================================
  File inventory: 2 entries
  Combined inventory: 2 entries
  Written: output/test_games/ports/gamelist_updated.xml

============================================================
AUDIT REPORT: ports
============================================================
Total games in gamelist.xml: 2
Matched to metadata: 0 (0.0%)
Unmatched: 2
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  diabdat
  tyrian21
============================================================


============================================================
PLATFORM: psx -> Sony Playstation
  source=files_only  strict_extensions=True
============================================================
  File inventory: 304 entries
  Combined inventory: 304 entries
  Written: output/test_games/psx/gamelist_updated.xml

============================================================
AUDIT REPORT: Sony Playstation
============================================================
Total games in gamelist.xml: 304
Matched to metadata: 0 (0.0%)
Unmatched: 304
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Vib-Ribbon
  Sled Storm
  Tenchu - Stealth Assassins
  Klaymen 1
  LSD - Dream Emulator
============================================================


============================================================
PLATFORM: saturn -> Sega Saturn
  source=files_only  strict_extensions=True
============================================================
  File inventory: 6 entries
  Combined inventory: 6 entries
  Written: output/test_games/saturn/gamelist_updated.xml

============================================================
AUDIT REPORT: Sega Saturn
============================================================
Total games in gamelist.xml: 6
Matched to metadata: 0 (0.0%)
Unmatched: 6
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Darius Gaiden
  Mr Bones
  Radiant Silvergun
  Legend of Oasis, The
  Nights Into Dreams
============================================================


============================================================
PLATFORM: segacd -> Sega CD
  source=files_only  strict_extensions=True
============================================================
  File inventory: 29 entries
  Combined inventory: 29 entries
  Written: output/test_games/segacd/gamelist_updated.xml

============================================================
AUDIT REPORT: Sega CD
============================================================
Total games in gamelist.xml: 29
Matched to metadata: 0 (0.0%)
Unmatched: 29
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Heart of the Alien - Out of This World Parts I and II
  Silpheed
  Road Avenger
  Flink
  Lords of Thunder
============================================================


============================================================
PLATFORM: snes -> Super Nintendo Entertainment System
  source=files_only  strict_extensions=True
============================================================
  File inventory: 1038 entries
  Combined inventory: 1038 entries
  Written: output/test_games/snes/gamelist_updated.xml

============================================================
AUDIT REPORT: Super Nintendo Entertainment System
============================================================
Total games in gamelist.xml: 1038
Matched to metadata: 0 (0.0%)
Unmatched: 1038
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Ultimate Fighter
  Hagane
  Monstania # SNES
  SOS
  Front Mission - Gun Hazard # SNES
============================================================


============================================================
PLATFORM: tg16 -> NEC TurboGrafx-16
  source=files_only  strict_extensions=True
============================================================
  File inventory: 664 entries
  Combined inventory: 664 entries
  Written: output/test_games/tg16/gamelist_updated.xml

============================================================
AUDIT REPORT: NEC TurboGrafx-16
============================================================
Total games in gamelist.xml: 664
Matched to metadata: 0 (0.0%)
Unmatched: 664
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  City Bomber Vx x
  Ganbare Golf Boys
  Ordyne Sounds
  Gomola Speed
  Echo by Trilinear
============================================================


============================================================
SUMMARY: 23/23 platforms processed successfully
============================================================
  amiga: inventory=154 matched=0
  atari2600: inventory=822 matched=0
  bios: inventory=821 matched=0
  c64: inventory=6000 matched=0
  doom: inventory=6 matched=0
  dreamcast: inventory=13 matched=0
  fba: inventory=985 matched=0
  fbneo: inventory=211 matched=0
  gba: inventory=1211 matched=0
  mame: inventory=1936 matched=0
  mastersystem: inventory=420 matched=0
  megadrive: inventory=1083 matched=0
  n64: inventory=217 matched=0
  neogeo: inventory=205 matched=0
  nes: inventory=1290 matched=0
  pc: inventory=269 matched=0
  pcengine: inventory=346 matched=0
  ports: inventory=2 matched=0
  psx: inventory=304 matched=0
  saturn: inventory=6 matched=0
  segacd: inventory=29 matched=0
  snes: inventory=1038 matched=0
  tg16: inventory=664 matched=0

## End-to-end: metadata enrichment from `.pkl`

Load the cleaned metadata dataset and use it to match & enrich gamelist entries.
You can pass `metadata_path=` directly instead of loading into a variable first.

In [8]:
# Load the metadata dataset once
METADATA_PATH = 'output/cleaned_df.pkl'

game_df = load_metadata(METADATA_PATH)
print(f"Metadata loaded: {game_df.shape[0]} games, {game_df['platform'].nunique()} platforms")
display(game_df.head(3))

Metadata loaded: 447295 games, 327 platforms

,platform,name,filename,summary,release_date,release_year,genres,developer,publisher,players,cooperative,rating,user_rating
0,Android,&0,NaN,Detective otome game.,2022-05-30,2022,"Simulator, Visual Novel",Coly,Coly,<NA>,<NA>,<NA>,NaN
1,iOS,&0,NaN,Detective otome game.,2022-05-30,2022,"Simulator, Visual Novel",Coly,Coly,<NA>,<NA>,<NA>,NaN
2,Mac,0 = 0 = 0,NaN,Connect numbers together while diving deeper a...,2020-05-15,2020,Puzzle,kultisti,NaN,<NA>,<NA>,<NA>,NaN

In [9]:
# Single platform with metadata: scan ROMs + match against dataset
result_enriched = build_platform_gamelist(
    test_root / 'nes',
    output_path=Path('output/test_games/nes/gamelist_enriched.xml'),
    game_df=game_df,
    source='files_only',
)
print(f"Inventory: {result_enriched['inventory_count']}, Matched: {result_enriched['matched_count']}, Rate: {result_enriched['match_rate']:.1%}")

============================================================
PLATFORM: nes -> Nintendo Entertainment System
  source=files_only  strict_extensions=True
============================================================
  File inventory: 1290 entries
  Combined inventory: 1290 entries
  Written: output/test_games/nes/gamelist_enriched.xml

============================================================
AUDIT REPORT: Nintendo Entertainment System
============================================================
Total games in gamelist.xml: 1290
Matched to metadata: 1214 (94.1%)
Unmatched: 76
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Nintendo Test Cart
  NES Test Cart
  PebbleBeachGolf
  JordanVsBird
  Maluex
============================================================

Inventory: 1290, Matched: 1214, Rate: 94.1%

In [10]:
# Verify enriched XML has metadata fields
import xml.etree.ElementTree as ET

tree = ET.parse('output/test_games/nes/gamelist_enriched.xml')
root = tree.getroot()
games = root.findall('game')
print(f"Total game entries: {len(games)}")

# Show a sample enriched entry
for game in games[:5]:
    name = game.findtext('name', '?')
    desc = game.findtext('desc', '')
    dev = game.findtext('developer', '')
    pub = game.findtext('publisher', '')
    print(f"  {name[:40]:40s}  dev={dev[:20]:20s}  pub={pub[:20]:20s}  desc={'yes' if desc else 'no'}")

Total game entries: 1290
  Trojan                                    dev=Capcom, Romstar Inco  pub=Capcom                desc=yes
  Mad Max                                   dev=Gray Matter, Mindsca  pub=Mindscape             desc=yes
  Pictionary - The Game of Video Quick Dra  dev=Software Creations    pub=LJN                   desc=yes
  1991 Du Ma Racing                         dev=Idea-Tek, Inc.        pub=Super Mega            desc=yes
  Fatal Fury 2                              dev=Cony Soft             pub=Cony Soft             desc=yes

In [11]:
# Alternative: pass metadata_path directly (loads pkl internally)
# Useful when you don't need the DataFrame in your notebook scope.
result_via_path = build_platform_gamelist(
    Path('lists/nes'),
    output_path=Path('output/test_games/nes/gamelist_xml_enriched.xml'),
    metadata_path=METADATA_PATH,
    source='xml_only',
)
print(f"Inventory: {result_via_path['inventory_count']}, Matched: {result_via_path['matched_count']}, Rate: {result_via_path['match_rate']:.1%}")

============================================================
PLATFORM: nes -> Nintendo Entertainment System
  source=xml_only  strict_extensions=True
============================================================
  XML inventory: 1184 entries
  Combined inventory: 1184 entries
  Written: output/test_games/nes/gamelist_xml_enriched.xml

============================================================
AUDIT REPORT: Nintendo Entertainment System
============================================================
Total games in gamelist.xml: 1184
Matched to metadata: 1183 (99.9%)
Unmatched: 1
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  DÃ©jÃ  Vu
============================================================

Inventory: 1184, Matched: 1183, Rate: 99.9%

In [12]:
# Multi-platform with metadata: process selected platforms
results_enriched = build_all_gamelists(
    test_root,
    output_root=Path('output/test_games'),
    platform_keys=['nes', 'gb', 'genesis'],
    game_df=game_df,
    source='files_only',
)
for r in results_enriched:
    status = 'OK' if r.get('success') else 'FAIL'
    print(f"  [{status}] {r.get('platform_key'):12s}  inventory={r.get('inventory_count', 0):5d}  matched={r.get('matched_count', 0):5d}  rate={r.get('match_rate', 0):.1%}")

============================================================
PLATFORM: nes -> Nintendo Entertainment System
  source=files_only  strict_extensions=True
============================================================
  File inventory: 1290 entries
  Combined inventory: 1290 entries
  Written: output/test_games/nes/gamelist_updated.xml

============================================================
AUDIT REPORT: Nintendo Entertainment System
============================================================
Total games in gamelist.xml: 1290
Matched to metadata: 1214 (94.1%)
Unmatched: 76
Low confidence matches (<80): 0

--- No Match Found (sample) ---
  Nintendo Test Cart
  NES Test Cart
  PebbleBeachGolf
  JordanVsBird
  Maluex
============================================================

  Skipping gb: not a directory
  Skipping genesis: not a directory

============================================================
SUMMARY: 1/1 platforms processed successfully
============================================================
  [OK] nes           inventory= 1290  matched= 1214  rate=94.1%